// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFmKggMYpsj6pKW3A0Hnh69l6Q7Oe2PPI',
    appId: '1:305266800160:web:8dd0943464d8719b906e45',
    messagingSenderId: '305266800160',
    projectId: 'flutter-maps-2025',
    authDomain: 'flutter-maps-2025.firebaseapp.com',
    storageBucket: 'flutter-maps-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTfUH4t8CrdEVh2vIWfwDwUyRvlhhMHaE',
    appId: '1:305266800160:android:f9400fadc9defc79906e45',
    messagingSenderId: '305266800160',
    projectId: 'flutter-maps-2025',
    storageBucket: 'flutter-maps-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzksRw-crDyVs9giKoJ4Lm_Z_A3MkDsVE',
    appId: '1:305266800160:ios:7cca5230f0017799906e45',
    messagingSenderId: '305266800160',
    projectId: 'flutter-maps-2025',
    storageBucket: 'flutter-maps-2025.firebasestorage.app',
    iosBundleId: 'com.example.flutterMaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzksRw-crDyVs9giKoJ4Lm_Z_A3MkDsVE',
    appId: '1:305266800160:ios:7cca5230f0017799906e45',
    messagingSenderId: '305266800160',
    projectId: 'flutter-maps-2025',
    storageBucket: 'flutter-maps-2025.firebasestorage.app',
    iosBundleId: 'com.example.flutterMaps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFmKggMYpsj6pKW3A0Hnh69l6Q7Oe2PPI',
    appId: '1:305266800160:web:fa19693829aeef28906e45',
    messagingSenderId: '305266800160',
    projectId: 'flutter-maps-2025',
    authDomain: 'flutter-maps-2025.firebaseapp.com',
    storageBucket: 'flutter-maps-2025.firebasestorage.app',
  );

}